server:
  type: dev
  port: 9080
  servlet:
    context-path: /
spring:
  jwt:
    headerKey:
    secret:
    before_len:
  api-key:
  aes.key:
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true

    properties:
      hibernate:
        ddl-auto: none
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        jdbc.time_zone: Asia/Seoul
  datasource:
    mst:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:oracle:thin:@{주소}:{포트}:{서비스명}
      jdbc-url: jdbc:log4jdbc:oraclethin:@{주소}:{포트}:{서비스명}
      username:
      password:
      maximum-pool-size: 2

aws:
  bucket:

mybatis:
  type-aliases-package: com.aplab.apsite.service
  mapper-locations: /**/mapper/*.xml
  show-sql: true

logging:
  level:
    org:
      springframework:
        web: error
        security: error
    '[com.aplab.apsite]': debug
    '[com.aplab.apsite.mapper]': error
